color0 #53443b
color1 #ffb4ab
color2 #ffb689
color3 #e8bea6
color4 #cacb78
color5 #ffb689
color6 #e8bea6
color7 #ede0da
color8 #a08d83
color9 #ffb4ab
color10 #ffb689
color11 #e8bea6
color12 #cacb78
color13 #ffb689
color14 #e8bea6
color15 #ede0da

cursor                #ede0da
cursor_text_color     #18120f
background            #18120f
foreground            #ede0da
selection_foreground  #d8c2b7
selection_background  #53443b
active_border_color   #ffb689
inactive_border_color #53443b
url_color             #ffb689

active_tab_foreground   #512300
active_tab_background   #ffb689
inactive_tab_foreground #d8c2b7
inactive_tab_background #53443b
cursor_trail_color      #d8c2b7
